version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: st1580
      POSTGRES_PASSWORD: st1580
      PGDATA: /st1580
    volumes:
      - postgres:/st1580
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: